#! /usr/bin/python3
# coding=utf-8
#
# simple git update for set pulling from core modules
#
import os
import sys



# check where we are and load default directory
if os.path.isdir("/usr/share/aptt"):
    if not os.path.isfile("se-toolkit"):
        os.chdir("/usr/share/aptt")
        sys.path.append("/usr/share/aptt")

import src.core.apttcore as core

# if we can't see our config then something didn't go good..
if not os.path.isfile("/etc/aptt/set.config"):
    core.print_error("Cannot locate APTT executable. Try running from the local directory.")
    core.print_error("If this does not work, please run the setup.py install file.")
    sys.exit()

try:
    # pull update set from the core libraries
    core.update_set()

# except keyboard interrupts
except KeyboardInterrupt:
    print("\n[!] Control-C detected. Exiting updating APTT.")

# handle all other errors
except Exception as e:
    print("\n[!] Something went wrong.. Printing the error: {0}".format(e))
